### ISSUE TITLE
Rendering difference between cloud and lite

### ISSUE THREAD

**Issue by bartvollebregt** [structurizr/cloud#21]
### Description

Hi! I have a setup where I write the model locally in the structurizr DSL. Then use Structurizr lite to view, validate and manually update the layout of the components.

Then I'm pushing both the .dsl and .json files to Git (Gitlab) and push the workspace to Structurizr cloud using Gitlab CI. In case you're interested, here's the .gitlab-ci.yml I'm using:

```
 
stages:
  - verify
  - validate
  - deploy

validate-dsl:
  stage: validate
  only:
    - merge_requests
  image:
    name: structurizr/cli:latest
    entrypoint: [""]
  script:
    - /usr/local/structurizr-cli/structurizr.sh validate -workspace landscape.dsl

push-to-structurizr-cloud:
  stage: deploy
  only:
    - main
  image:
    name: structurizr/cli:latest
    entrypoint: [""]
  script:
    - /usr/local/structurizr-cli/structurizr.sh push -id $STRUCTURIZR_WORKSPACE_ID -key $STRUCTURIZR_CLOUD_KEY -secret $STRUCTURIZR_CLOUD_SECRET -workspace landscape.json

```

Now, I'm seeing difference in the layout between Structurizr Lite and Structurizr Cloud.
Specifically it seems one or two components aren't in the right place in the Cloud version.

I'd prefer not to share screenshots of our architecture publicly, but can provide the specifc files when requested privately.

### Steps to reproduce

1. Write a DSL file for a complex architecture locally
2. View the DSL file in Structurizr Lite and update the layout manually
3. Push the workspace to Structurizr Cloud using the CLI.
4. Check the difference in results between cloud and lite

### Configuration

Structurizr Lite using docker. Here's the docker compose file. Using "latest"

```
services:
  structurizr:
    container_name: structurizr
    image: structurizr/lite

    ports:
      - "8090:8080"
    environment:
      - STRUCTURIZR_WORKSPACE_FILENAME=landscape
    volumes:
      - ".:/usr/local/structurizr:rw"

```

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free
